### ISSUE TITLE
Backend module only allowed in live workspace

### ISSUE THREAD

**Issue by rbnzlknb** [fnagel/t3extblog#275]
Please allow the blog backend module in all workspaces.

**Comment by fnagel** [comment]
Sure, I can do that. I need to configure it like described here, right? https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Workspaces/Index.html#workspaces-backend-acess

The extension was not tested with workspaces in some time. Any feedback on this?

**Comment by rbnzlknb** [comment]
Correct, it should be solved with this configuration:
```
return [
    'web_T3extblogBlogsystem' => [
        'parent' => 'web',
        'position' => ['after' => 'web_info'],
        'access' => 'user,group',
        'workspaces' => '*',
        // ... other configuration
    ],
];
```

In my experience, the extension works with workspaces.

However, there is a problem with content elements that are attached to a post.
If a published post is edited in the non-live workspace and content elements are added, the sorting in the FE is not correct. 
After publishing, the frontend display is correct.

However, it seems to be more of a core problem.
https://forge.typo3.org/issues/99426

**Comment by fnagel** [comment]
I've pushed a small fix with the needed configuration. Please check and and give feedback if this is sufficient.

Regarding the sorting issue: yes, that sounds like the linked core issue indeed. T3extblog uses a TypoScript rendering approach for its tt_content records as EXT:news does. Would be interesting if the News extension has the same issues.

We could try to create a workaround when in workspace mode?

**Comment by rbnzlknb** [comment]
With this change, the backend module is also visible in other workspaces.

However, there is still a problem in the backend post list.

Illegal offset type in isset or empty  
`if (isset($sysLanguageUid) && isset($translations['translations'][$sysLanguageUid])) {`
https://github.com/fnagel/t3extblog/blob/master/Classes/ViewHelpers/Backend/LocalizationViewHelper.php#L89

If I understand correctly, $sysLanguageUid is not 'sys_language_uid' but an array.

`$sysLanguageUid = $sysLanguageUid['sys_language_uid'];`  
This allows me to call up the list in the backend. 

However, the corresponding post icon is still missing for translated posts.

**Comment by fnagel** [comment]
@rbnzlknb Sorry for the late response. Not much time for OSS at the moment.

Can you check if the PR I just merged (#279 and #280) fixed the issues for you? Should be the fix for your issue. It's included in the latest master.

**Comment by rbnzlknb** [comment]
The current master version fixes the issue.

Thanks for the fix.

**Comment by fnagel** [comment]
Wonderful. Thanks for the feedback!

Released with v8.0.2
